add temporary agent graph tutorial; convert to nbformat: 4, nbformat_minor: 5
nbformat.NBFormatError: Unsupported nbformat version 5;
ref. https://github.com/jupyter/nbviewer/issues/545